# Generated by Django 2.2.4 on 2019-09-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subject',
        ),
    ]
